version: "3.9"
services:
  get_file_list_function:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8081:8080
    environment:
      SLACK_API_TOKEN: token
    volumes:
      - ./src:/var/task
