version: "3.9"
services:
  get-file-list-function:
    image: local:get-file-list-function
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      SLACK_API_TOKEN: token
