version: "3.9"
services:
  start-execution:
    image: local:start-execution
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8082:8080
    environment:
      STAGE: local
      SLACK_SIGNING_SECRET: secret
    volumes:
      - ./src:/var/task
